# Generated by Django 4.2.15 on 2024-09-10 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_description', models.TextField()),
                ('venue_blurb', models.TextField(blank=True)),
                ('venue_capacity', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved')], default=0)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venue_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-venue_name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('Corporate', 'Corporate Event'), ('Other', 'Other'), ('Special Occasion', 'Special Occasion'), ('Gala', 'Gala Event'), ('Workshop', 'Workshop'), ('Wedding', 'Wedding')], max_length=20)),
                ('event_date', models.DateField()),
                ('num_guests', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venue_bookings', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.venue')),
            ],
            options={
                'ordering': ['event_date', '-client_id'],
            },
        ),
    ]
