# Generated by Django 4.2.15 on 2024-09-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Corporate', 'Corporate Event'), ('Other', 'Other'), ('Special Occasion', 'Special Occasion'), ('Wedding', 'Wedding'), ('Gala', 'Gala Event')], max_length=20),
        ),
    ]
