# Generated by Django 4.2.15 on 2024-09-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('COR', 'Corporate Event'), ('WED', 'Wedding'), ('GAL', 'Gala Event'), ('OCC', 'Special Occasion'), ('WSP', 'Workshop'), ('OTH', 'Other')], max_length=3),
        ),
    ]
