# Generated by Django 4.2.15 on 2024-09-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('OCC', 'Special Occasion'), ('COR', 'Corporate Event'), ('WSP', 'Workshop'), ('OTH', 'Other'), ('GAL', 'Gala Event'), ('WED', 'Wedding')], max_length=3),
        ),
    ]
