# Generated by Django 4.2.15 on 2024-09-13 11:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Gala', 'Gala Event'), ('Other', 'Other'), ('Workshop', 'Workshop'), ('Special Occasion', 'Special Occasion'), ('Corporate', 'Corporate Event')], max_length=20),
        ),
    ]
