# Generated by Django 4.2.15 on 2024-09-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Other', 'Other'), ('Corporate', 'Corporate Event'), ('Wdding', 'Wedding'), ('Gala', 'Gala Event'), ('Special Occasion', 'Special Occasion'), ('Workshop', 'Workshop')], max_length=20),
        ),
    ]
