# Generated by Django 4.2.15 on 2024-08-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved')], default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('OCC', 'Special Occasion'), ('WSP', 'Workshop'), ('COR', 'Corporate Event'), ('OTH', 'Other'), ('WED', 'Wedding'), ('GAL', 'Gala Event')], max_length=3),
        ),
    ]
