# Generated by Django 4.2.15 on 2024-09-16 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_venue_featured_image_alter_booking_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Special Occasion', 'Special Occasion'), ('Gala', 'Gala Event'), ('Workshop', 'Workshop'), ('Other', 'Other'), ('Corporate', 'Corporate Event')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_guests',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(20)]),
        ),
    ]
