# Generated by Django 4.2.15 on 2024-08-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_status_alter_booking_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.AutoField(default='001', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('COR', 'Corporate Event'), ('WSP', 'Workshop'), ('GAL', 'Gala Event'), ('OTH', 'Other'), ('WED', 'Wedding'), ('OCC', 'Special Occasion')], max_length=3),
        ),
    ]
