# Generated by Django 4.2.15 on 2024-08-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_venue_status_alter_booking_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='venue_slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('OTH', 'Other'), ('OCC', 'Special Occasion'), ('GAL', 'Gala Event'), ('WSP', 'Workshop'), ('COR', 'Corporate Event'), ('WED', 'Wedding')], max_length=3),
        ),
    ]
