# Generated by Django 4.2.15 on 2024-09-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Other', 'Other'), ('Wedding', 'Wedding'), ('Workshop', 'Workshop'), ('Corporate', 'Corporate Event'), ('Special Occasion', 'Special Occasion'), ('Gala', 'Gala Event')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('venue_name', 'venue_capacity'), name='unique_venue_key_capacity', violation_error_message='Number of guests exceeds venue capacity.'),
        ),
    ]
