# Generated by Django 4.2.15 on 2024-08-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_venue_slug_venue_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('OCC', 'Special Occasion'), ('COR', 'Corporate Event'), ('WED', 'Wedding'), ('WSP', 'Workshop'), ('OTH', 'Other'), ('GAL', 'Gala Event')], max_length=3),
        ),
    ]
