# Generated by Django 4.2.15 on 2024-09-16 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_event_type_alter_booking_num_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Special Occasion', 'Special Occasion'), ('Gala', 'Gala Event'), ('Workshop', 'Workshop'), ('Wedding', 'Wedding'), ('Corporate', 'Corporate Event'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_guests',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(500, message='Guest count cannot exceed 500 guests'), django.core.validators.MinValueValidator(20, message='Guest count requires a mimum of 20 guests')]),
        ),
    ]
