# Generated by Django 4.2.15 on 2024-08-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_id_remove_venue_venue_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_date',
            field=models.DateField(unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('GAL', 'Gala Event'), ('OTH', 'Other'), ('WED', 'Wedding'), ('OCC', 'Special Occasion'), ('COR', 'Corporate Event'), ('WSP', 'Workshop')], max_length=3),
        ),
    ]
