# Generated by Django 4.2.15 on 2024-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['event_date', '-client_id']},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Corporate', 'Corporate Event'), ('Other', 'Other'), ('Gala', 'Gala Event'), ('Workshop', 'Workshop'), ('Special Occasion', 'Special Occasion')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('event_date', 'venue'), name='booking_unique_date_venue', violation_error_message='Booking with this Venue already exits.'),
        ),
    ]
