# Generated by Django 4.2.15 on 2024-09-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Other', 'Other'), ('Corporate', 'Corporate Event'), ('Gala', 'Gala Event'), ('Wedding', 'Wedding'), ('Workshop', 'Workshop'), ('Special Occasion', 'Special Occasion')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('venue', 'num_guests')},
        ),
    ]
