# Generated by Django 4.2.15 on 2024-09-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_event_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='venue',
            name='unique_venue_key_capacity',
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Special Occasion', 'Special Occasion'), ('Other', 'Other'), ('Corporate', 'Corporate Event'), ('Workshop', 'Workshop'), ('Gala', 'Gala Event')], max_length=20),
        ),
    ]
