# Generated by Django 4.2.15 on 2024-08-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('WSP', 'Workshop'), ('OTH', 'Other'), ('COR', 'Corporate Event'), ('WED', 'Wedding'), ('OCC', 'Special Occasion'), ('GAL', 'Gala Event')], max_length=3),
        ),
    ]
