# Generated by Django 4.2.15 on 2024-08-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_event_date_alter_booking_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_date',
            field=models.DateField(unique_for_date='event_date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('WED', 'Wedding'), ('OCC', 'Special Occasion'), ('COR', 'Corporate Event'), ('GAL', 'Gala Event'), ('OTH', 'Other'), ('WSP', 'Workshop')], max_length=3),
        ),
    ]
