# Generated by Django 4.2.15 on 2024-09-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_venue_unique_venue_key_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_unique_date_venue',
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Gala', 'Gala Event'), ('Corporate', 'Corporate Event'), ('Other', 'Other'), ('Special Occasion', 'Special Occasion'), ('Workshop', 'Workshop')], max_length=20),
        ),
    ]
