# Generated by Django 4.2.15 on 2024-08-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_event_date_alter_booking_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('WED', 'Wedding'), ('COR', 'Corporate Event'), ('OCC', 'Special Occasion'), ('GAL', 'Gala Event'), ('WSP', 'Workshop'), ('OTH', 'Other')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('venue', 'event_date')},
        ),
    ]
