# Generated by Django 4.2.15 on 2024-09-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('OCC', 'Special Occasion'), ('OTH', 'Other'), ('WSP', 'Workshop'), ('GAL', 'Gala Event'), ('WED', 'Wedding'), ('COR', 'Corporate Event')], max_length=3),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
