# Generated by Django 4.2.15 on 2024-09-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_event_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Corporate', 'Corporate Event'), ('Workshop', 'Workshop'), ('Other', 'Other'), ('Gala', 'Gala Event'), ('Special Occasion', 'Special Occasion')], max_length=20),
        ),
    ]
