# Generated by Django 4.2.15 on 2024-09-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_booking_unique_date_venue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Special Occasion', 'Special Occasion'), ('Gala', 'Gala Event'), ('Corporate', 'Corporate Event'), ('Other', 'Other'), ('Wedding', 'Wedding'), ('Workshop', 'Workshop')], max_length=20),
        ),
    ]
