# Generated by Django 4.2.15 on 2024-09-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Wedding', 'Wedding'), ('Gala', 'Gala Event'), ('Special Occasion', 'Special Occasion'), ('Corporate', 'Corporate Event'), ('Other', 'Other')], max_length=20),
        ),
    ]
