# Generated by Django 4.2.15 on 2024-08-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_event_date_alter_booking_event_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-event_date', '-created_on']},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['-venue_name']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('WSP', 'Workshop'), ('WED', 'Wedding'), ('OCC', 'Special Occasion'), ('COR', 'Corporate Event'), ('OTH', 'Other'), ('GAL', 'Gala Event')], max_length=3),
        ),
    ]
