# Generated by Django 4.2.15 on 2024-09-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Special Occasion', 'Special Occasion'), ('Wedding', 'Wedding'), ('Gala', 'Gala Event'), ('Corporate', 'Corporate Event'), ('Other', 'Other'), ('Workshop', 'Workshop')], max_length=20),
        ),
    ]
