# Generated by Django 4.2.15 on 2024-08-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_options_alter_venue_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-event_date', '-client_id']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('OCC', 'Special Occasion'), ('COR', 'Corporate Event'), ('GAL', 'Gala Event'), ('OTH', 'Other'), ('WED', 'Wedding'), ('WSP', 'Workshop')], max_length=3),
        ),
    ]
