# Generated by Django 4.2.15 on 2024-09-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Corporate', 'Corporate Event'), ('Workshop', 'Workshop'), ('Gala', 'Gala Event'), ('Special Occasion', 'Special Occasion'), ('Other', 'Other')], max_length=20),
        ),
    ]
