# Generated by Django 4.2.15 on 2024-08-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_options_alter_booking_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('OCC', 'Special Occasion'), ('WED', 'Wedding'), ('OTH', 'Other'), ('GAL', 'Gala Event'), ('COR', 'Corporate Event'), ('WSP', 'Workshop')], max_length=3),
        ),
    ]
