# Generated by Django 4.2.15 on 2024-09-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Other', 'Other'), ('Workshop', 'Workshop'), ('Gala', 'Gala Event'), ('Wedding', 'Wedding'), ('Special Occasion', 'Special Occasion'), ('Corporate', 'Corporate Event')], max_length=20),
        ),
    ]
