# Generated by Django 4.2.15 on 2024-09-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_email_alter_booking_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Gala', 'Gala Event'), ('Wedding', 'Wedding'), ('Special Occasion', 'Special Occasion'), ('Other', 'Other'), ('Corporate', 'Corporate Event')], max_length=20),
        ),
    ]
