# Generated by Django 4.2.15 on 2024-10-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_booking_event_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Contact',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_unique_date_venue',
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Special Occasion', 'Special Occasion'), ('Other', 'Other'), ('Workshop', 'Workshop'), ('Gala', 'Gala Event'), ('Corporate', 'Corporate Event')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('event_date', 'venue'), name='booking_unique_date_venue', violation_error_message='Booking with Venue already exits.'),
        ),
    ]
